apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-renovate
  namespace: renovate
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "renovate"
          serviceAccountRef:
            name: renovate-vault-auth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secret
  namespace: renovate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-renovate
    kind: SecretStore
  target:
    name: renovate-secret
    creationPolicy: Owner
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: renovate
        property: github_token
