apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../apps/memos
- ../../../apps/monitoring
- ../../../apps/it-tools
- ../../../apps/uptime-kuma
- ../../../apps/gotify
- ../../../apps/wud
- ../../../apps/family-status
