apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotify-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 1Gi
