apiVersion: v1
kind: Pod
metadata:
  name: memos-pvc
  namespace: apps
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: memos-data
      mountPath: /data
  volumes:
  - name: memos-data
    persistentVolumeClaim:
      claimName: memos-data
