apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memos-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
  volumeName: pvc-0da440a2-f32b-493f-bb31-fecff0c3a28e
