apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memos-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
