apiVersion: apps/v1
kind: Deployment
metadata:
  name: wud
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wud
  template:
    metadata:
      labels:
        app: wud
    spec:
      containers:
        - name: wud
          image: getwud/wud:latest
          ports:
            - containerPort: 3000
          env:
            - name: WUD_WATCHER_LOCAL_CRON
              value: "0 */6 * * *"
            - name: WUD_SERVER_PORT
              value: "3000"
            - name: WUD_UI_ENABLED
              value: "true"
