apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: family-quiz
  namespace: my-apps
spec:
  ingressClassName: traefik
  rules:
    - host: quiz.porcocan.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: family-quiz
                port:
                  number: 80
