apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gotify
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
    - host: gotify.itworksonmycluster.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gotify
                port:
                  number: 80
