apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghost
  namespace: apps
  annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
      traefik.ingress.kubernetes.io/forwarded-headers.insecure: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: itworksonmycluster.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ghost
                port:
                  number: 80
