apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memos
  namespace: apps
spec:
  ingressClassName: traefik
  rules:
    - host: memos.itworksonmycluster.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: memos
                port:
                  number: 80
