apiVersion: apps/v1
kind: Deployment
metadata:
  name: family-status
  namespace: my-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: family-status
  template:
    metadata:
      labels:
        app: family-status
    spec:
      nodeSelector:
        kubernetes.io/hostname: kubernetes

      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

      containers:
        - name: family-status
          image: family-status:v1.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8333
          env:
            - name: NEWS_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: family-status-news-bot
                  key: NEWS_BOT_TOKEN
