apiVersion: v1
kind: Service
metadata:
  name: family-status
  namespace: my-apps
  labels:
    app: family-status
spec:
  type: ClusterIP
  selector:
    app: family-status
  ports:
    - name: http
      port: 80
      targetPort: 8333
