apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkwarden
  namespace: apps
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: linkwarden
  template:
    metadata:
      labels:
        app: linkwarden
    spec:
      containers:
        - name: linkwarden
          image: ghcr.io/linkwarden/linkwarden:latest
          ports:
            - containerPort: 3000

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: linkwarden-secret
                  key: DATABASE_URL

            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: linkwarden-secret
                  key: NEXTAUTH_SECRET
