---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linkwarden-secret
  namespace: apps
spec:
  encryptedData:
    DATABASE_URL: AgA/Kva+g9nFYRE0S+IaQ0krMDF5BMlG1zADphOaTraaJwGxVfEWbMgNuqs8LmefHbpqxqaQKXmo41WVwXIuKJT52p2PIRVFbpSylWbZ+LMMijpPf5L/V/oWfaaRF5bwzcpxQ8w/fseAzvwmb9+E/qyD8Gnn9s1pE16B02l0+QnItLwo9r7ATC3MIDFw2TAV1uOnZwiRczqcKOQPw1/aXRf10gmGS3yDbYqdzS+sQhw4cXku3L6lWtQRWRH0qHqKiuCmdVZ9SEdF7d7blOFCqW3EQGi8kDfZU4pCNH4JIEJg4RP6LpO7WGbsl9xfECoBGzv/pUjxCala6vbp0hudaaEaDbu7cu1vdMdfXhtJYWcE5oLBJ8t+T/bHHjhdMawTF6JOvBRixcOM4S1iLrsdSTHm0wvjWgQ9lH6yN6DysJlvrWpasf7jZuFgC01i0/AePdaYO5HjC4TQtO5r5JIQdEa/uD04tZe0OS6YmhpOgFuQ4Iu2l+Iy+1iYSVGo183HfFgwhdbJSqyRfIdoYXf3RO7Oue9q+jiFat0RSqBkz+45SYjLk+8QNoAAzPRa4IqWthLdlunG+KJJb43Zcb7NJA2THlLg6mJeb0bTGhE7jBRfiMTkrdV8IwTIS2GAX3Y+d0lK8nO8UMQrAbUCrGkVFcdtYRLHgaiA4b3ho1XUuefG6UfzythPFXowzAa4Bqtvd0MA4V1LHJStrZkps0fy47jY85sAcMjGiBi/RkmFBDjt8fphENjIYL9ma4hOoVJJk1tKtaRFKklVN5qiZJhZOSoHLB81bfIUAEUE7lxv8kfwhEPazZHFqA==
    NEXTAUTH_SECRET: AgAHFpjKeBJIyc2vqWxYsdE+J+HmHCXWaF78sMqEGu2k+fyfCQKhJpLZbwUUrj0LRiW9c0QHbV2AysPJvptWMRdLZfJoe7fcQbLAU96mN9X+DMWTQsu2unCTc1qD0GIOoidBRM7A2ZxWpokdWPK+HSkeL+wuQseZTZEn+6JIS3PtbLoIDgT8OVj56Bsfzm+AbNORfAssiRCTujKzoTXp8xzToAHrOZASmE9PtROO++Liy1hVJG+ZWqc883ZJ/mmGp/tcJkolbOqRnfPr/3f2hWYqmf/3snL/cs+BB4SrgYhLmha8DJgG8WX05DLQTLXPhN8HM7znwZk1NFJFROxPHiwJsBIndspTCrJuplhwek9wwi5qHnen+fsSBmfq1tdDHCwpn1W7kEP21zMgXNSF7T7kHD0aO6+yCSVyTiSyzjzaN/dTp0lurTREyxSi1jIhhLDJqe0i+sXSiXlQXvAyEKx+Dz31+zXOFlfrkh+lSzUporwaQZLLPhUMNMDxozw5nWYnpga7Ebik/iNlC0atzQlxbGojIHqVeYPN8Psg/uNWw60U2sLUX/NXALRr8mg8lqkCB7hyfDTpTuowdpNNP9jevNkHTBI/6GFwEIfYqHDqtbmzctzVaCg6GKGqKL5N3nGzd9OMvyVbdz940vgteXmdFAjuXcQ7rUTX7A92iw6HVzVXY4BuvxzeYjt51e3Z5gfORn8ymtg7VjirKoQF+tyKjWcVjxn2RkvGC2qp/goH5xpnrtrcxXf3Lne1mA==
  template:
    metadata:
      name: linkwarden-secret
      namespace: apps
    type: Opaque
