---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linkwarden-secret
  namespace: apps
spec:
  encryptedData:
    DATABASE_URL: AgBwwM6c49xSWX1SdCZk+roEIvrlYqgstgPsfN1vPYSqcNwSoOuU+q1/2J8ebqV1YtGtVEuPItpdopnpb9SfShlclKgHI6cV3QjX/FcfPj59RLcfarpauQKIceQ13zFOcSsiTQIhuJItWSo7cgiKpQY/xdwpcJeFrI7EC6vtPo3JJXKdzCy297k/QI0iwJI1bBw4gE+OS5ifjvKtWX88LrokL2ZHuUj9/nabnpjuBnG6Nwb1LB4rzMQUsQVLqis9Wq8szlep1M1KMdZGJu9FvMD6DmGevpCyolutm1yG+J5Tx9IRXgDWPcYO+zxN5ue9iXnMCbGttXsF3Mx1ZGPCFf6iGCxyK9jjiZQ9fzwLVqNqvDnaMHobw/cksWFUu+c0vo/BltpQAtRvKS+/qlke+2q+4gdwenb8swU5fO08bLs/3OozirPXvfIsDs94VJ8Q6/svxwwb3XwBf1rYtOsBYPIdG4EidPzRFNVo6sSYFHU7qhQfPoN0YsLZJXIy+vEXvAl6Lilbmkajul/EysiHDfxShlJKiwe9/2ePtQu6yrZp5+Q2MutApQ3EG2JgiBe2ltEcl7pmCxxcaFQH793gKFUBJnTf9CMBumC/CmOINfKwv4+w/FCwUQqaQA5yJCRbecqBsd9SjHmOJjP5HI87jP6c/k8602Vc/dO9BOwX0JsfWtV/B40qYmImXK2o3rQ/e4IzlJmrhJLAEpoj/Ez88qfQi9lK3S0jVrb8/ENG3LSXGIJzaJMA
    NEXTAUTH_SECRET: AgAWyzaXCb3OZHQdMmDwYmAs8+eTxq6A5+8yfJ9f0B34+1rQFg/Xardsl241/mlHUaoP4F04QIxH7LfqsZHzFLR4Ne88dv715qYY0H4xTmq+2Yt6nc4Ctu3vpVZUneXKueICTiPUPeyC7QSANEcGJJApZnO+XkXtAGEJNCuT3howMbrIe3VtAQnP+mrJ7jwspxa3haju862ADNA/mUs3+rP2eZEDouQ0Uyl5ehwf024R6lfmsiLjra8yD/I53fAfWea9SX2t43qzxbH+by8yZnaWWMeGjuNiKZLVF9kHFYdGCei5XrxJqWKtzexdTDBiKW0DF6cbaizHlUfJjWzSHhSFCaWRkWKHhcvwiYI7rEaFzRervNYlEI/dXqJ40qmbnm8rpqUBhWFsbe8T20VKkycStUmEvmtmq9YHBuHBlSNewtBrPXnJpdcY1767k96HelDIxS3NaUldPN+8WLAIAIPNQMVz7+GYftGhNc9qqUjvggXIeqamJhdZndoytzZdEaWf1v130Se5Gm9QpjyS6HquWGZmHkxu/HjJK/jleAWBeHXp76rqUxN6RJgePyOfeSSWzIWAVt2pZkSZ14Zf7LGqMPm8I52topTTNqbseQAColyVg3/NPnWPENujfMUtiH5LJZMCxiDO5CFqtT9JjZgTFINKWQFbdLZokfE2qYXpacnOr+DtAq7xRuHDMyp7gXNU7AXhPK1S//VwiBPWaQ==
  template:
    metadata:
      name: linkwarden-secret
      namespace: apps
