apiVersion: apps/v1
kind: Deployment
metadata:
  name: muu
  namespace: my-apps
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: muu
  template:
    metadata:
      labels:
        app: muu
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8snode2
      containers:
        - name: muu
          image: muu:v1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: muu-data
              mountPath: /app/backend/data
      volumes:
        - name: muu-data
          persistentVolumeClaim:
            claimName: muu-data
