apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: muu-data
  namespace: my-apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 5Gi
