apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 30m
  timeout: 15m
  releaseName: vault

  chart:
    spec:
      chart: vault
      version: "0.32.0"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: vault
      interval: 12h

  install:
    createNamespace: false
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  values:
    injector:
      enabled: false

    ui:
      enabled: true
      serviceType: ClusterIP

    server:
      dataStorage:
        enabled: true
        size: 10Gi
        storageClass: longhorn-retain
        accessMode: ReadWriteOnce

      auditStorage:
        enabled: false

      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
          setNodeId: true
          config: |
            ui = true

            listener "tcp" {
              tls_disable = 1
              address         = "[::]:8200"
              cluster_address = "[::]:8201"
            }

            storage "raft" {
              path = "/vault/data"

              retry_join {
                leader_api_addr = "http://vault-0.vault-internal:8200"
              }

              retry_join {
                leader_api_addr = "http://vault-1.vault-internal:8200"
              }

              retry_join {
                leader_api_addr = "http://vault-2.vault-internal:8200"
              }
            }

            service_registration "kubernetes" {}

      affinity: |
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: vault
                  app.kubernetes.io/instance: vault
                  component: server
              topologyKey: kubernetes.io/hostname
